name: pdfviewer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  file_picker: ^8.0.6
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.3
  pdfx: ^2.6.0
  permission_handler: ^11.3.1
  receive_sharing_intent: ^1.8.0
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/


